services:
  db:
    image: mysql:8.0.33
    hostname: db
    command: --default-authentication-plugin=mysql_native_password --sql_mode="NO_ENGINE_SUBSTITUTION"
    volumes:
      - ./database/init/:/docker-entrypoint-initdb.d/
    environment:      
      MYSQL_ROOT_PASSWORD: pwd
    ports:
      - "3306:3306"    
    deploy:
      resources:
        limits:
          cpus: "0.56"
          memory: "400MB"

  # api01: &api
  #   build: .
  #   hostname: api01
  #   environment:      
  #     DB_HOST: db
  #   restart: always
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.37"
  #         memory: "60MB"
  
  # api02:
  #   <<: *api 
  #   hostname: api02

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - api01
  #     - api02
  #   ports:
  #     - "9999:9999"
  #   restart: always
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.2"
  #         memory: "30MB"